// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axpauyajwsootmkauvfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cGF1eWFqd3Nvb3Rta2F1dmZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjMxNDQsImV4cCI6MjA2MTM5OTE0NH0.rRvSty0QbiVCcb4FlgXJ_FmBRH5aMS87sLPtXWC_mWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);